PracticaAdoNet/Models/ViewModels/HeroeViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace PracticaAdoNet.Models.ViewModels
{
    public class HeroeViewModels 
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Clase { get; set; }
        public int Nivel { get; set; }
    }
}

PracticaAdoNet/Controllers/HeroeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PracticaAdoNet.Services;
using System.Threading.Tasks;
using PracticaAdoNet.DTOs;

namespace PracticaAdoNet.Controllers
{
    public class HeroeController : Controller
    {
        private readonly IHeroeService _heroeService;

        public HeroeController()
        {
            _heroeService = new HeroeService();
        }
        // GET: Heroe
        public async Task<ActionResult> Index()
        {
            var heroes = await _heroeService.GetAllHeroes();
            return View(heroes);
        }


        //Get por id
        public async Task<ActionResult> GetHeroeById(int id)
        {
            if (id == null || id <= 0) 
            {
                TempData["ErrorMessage"] = "El ID del héroe es inválido o no se ha proporcionado.";
                return RedirectToAction("Index"); 
            }

            try
            {
                
                var heroeEncontrado = await _heroeService.GetHeroeById(id);  

                if (heroeEncontrado == null)
                {
                    TempData["ErrorMessage"] = $"No se encontró un héroe con ID: {id}.";
                    return RedirectToAction("Index"); 
                }
                else
                {
               
                    return View(heroeEncontrado);
                }
            }
            catch (Exception ex)
            {
                
                TempData["ErrorMessage"] = $"Ocurrió un error al buscar el héroe con ID {id}: {ex.Message}";
                // Loguea la excepción para depuración
                Console.WriteLine($"Error al obtener héroe por ID: {ex}");
                return RedirectToAction("Index"); // Redirige a la página principal con el mensaje de error
            }
        }

        //Get: Create Heroe
        [HttpGet]
        public ActionResult CreateHeroe()
        {
            return View(new CreateHeroeDtos());
        }
        //POST: Create Heroe
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateHeroe(CreateHeroeDtos heroe)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    var newIdHeroe = await _heroeService.CreateHeroe(heroe);
                    TempData["MensajeExito"] = $"Heroe con nombre = {heroe.Nombre} y id = {newIdHeroe} creado con exito";
                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError("", "Ocurrió un error al crear el héroe: " + ex.Message);
                    return View(heroe); 
                }
                
            }else
            {
                return View(heroe);
            }
        }

        //Delete
        [HttpPost]
        [ValidateAntiForgeryToken] 
        public async Task<ActionResult> DeleteHeroeById(int id) 
        {
            if (id <= 0) 
            {
                TempData["ErrorMessage"] = "ID de héroe inválido para eliminación.";
                return RedirectToAction("Index");
            }

            try
            {
                var rowsAffected = await _heroeService.DeleteHeroeById(id);

                if (rowsAffected > 0) 
                {
                    TempData["MensajeExito"] = $"Héroe con ID {id} eliminado exitosamente.";
                }
                else
                {
                    TempData["ErrorMessage"] = $"No se encontró un héroe con ID {id} o no se pudo eliminar.";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Ocurrió un error al eliminar el héroe con ID {id}: {ex.Message}";
                Console.WriteLine($"Error al eliminar héroe: {ex}");
            }

           
            return RedirectToAction("Index");
        }

        //Update heroe
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UpdateHeroe(UpdateHeroeDtos heroe)
        {

            if(ModelState.IsValid)
            {
                var filasAfectadas = await _heroeService.UpdateHeroe(heroe);
                if(filasAfectadas <= 0)
                {
                    TempData["ErrorMessage"] = $"No se ha podido actualizar su heroe por que su heroe con id = {heroe.Id} no existe";
                    return RedirectToAction("Index");
                }
                TempData["MensajeExito"] = $"Se logro actualizar su heroe con id = {heroe.Id}";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["ErrorMessage"] = "Porfavor rellene bien el formulario";
                return View(heroe);
            }
        } 

        //get para formulario
        public async Task<ActionResult> FormularioEdicion(int id)
        {
            var datosHeroe = await _heroeService.GetHeroeById(id);

            return View(datosHeroe);
        }
    }
}

PracticaAdoNet/Views/Heroe/CreateHeroe.cshtml
@model PracticaAdoNet.DTOs.CreateHeroeDtos

@{
    ViewBag.Title = "CreateHeroe";
}

<h2>Bienvenidos a crear heroe:</h2>

@using(Html.BeginForm("CreateHeroe","Heroe",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Nombre)
        @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control", placeHolder = "Agrege el nombre de su heroe" })
        @Html.ValidationMessageFor(m => m.Nombre,"", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Clase)
        @Html.TextBoxFor(m => m.Clase, new { @class = "form-control", placeHolder = "Agrege la clase de su heroe" })
        @Html.ValidationMessageFor(m => m.Clase, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Nivel)
        @Html.TextBoxFor(m => m.Nivel, new { @class = "form-control", type = "number", min=1, max=1000 })
        @Html.ValidationMessageFor(m => m.Nivel, "", new { @class = "text-danger" })
    </div>

    <button class="btn btn-primary">
        Crear Heroe
    </button>
}

PracticaAdoNet/Views/Heroe/FormularioEdicion.cshtml
@model PracticaAdoNet.Models.ViewModels.HeroeViewModels
@{
    ViewBag.Title = "FormularioEdicion";
}

<h2>Formulario Edicion de heroe = @Model.Nombre</h2>


@if (TempData["MensajeExito"] != null)
{
    <div class="alert alert-success">@TempData["MensajeExito"]</div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}

@Html.ValidationSummary(true, "", new { @class = "text-danger" })

@using (Html.BeginForm("UpdateHeroe", "Heroe", FormMethod.Post))
{
    @Html.AntiForgeryToken();
    @Html.HiddenFor(m => m.Id);

    <div class="form-group">
        @Html.LabelFor(m => m.Nombre)
        @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control", value = Model.Nombre })
        @Html.ValidationMessageFor(m => m.Nombre, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Clase)
        @Html.TextBoxFor(m => m.Clase, new { @class = "form-control", value = Model.Clase })
        @Html.ValidationMessageFor(m => m.Clase, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Nivel)
        @Html.TextBoxFor(m => m.Nivel, new { @class = "form-control", value = Model.Nivel, min=1, max=1000 })
        @Html.ValidationMessageFor(m => m.Nivel, "", new { @class = "text-danger" })
    </div>

    <button type="submit" class="btn btn-primary">
        Actualizar Heroe
    </button>

    @Html.ActionLink("Cancelar", "Index", "Heroe", null, new { @class = "btn btn-default" })
}

PracticaAdoNet/Views/Heroe/GetHeroeById.cshtml
@model PracticaAdoNet.Models.ViewModels.HeroeViewModels
@{
    ViewBag.Title = "GetHeroeById";
}

@if(Model != null)
{
    <h1>Nombre = @Model.Nombre</h1>
    <p>Clase = @Model.Clase</p>
    <p>Nivel = @Model.Nivel</p>
}

PracticaAdoNet/Views/Heroe/Index.cshtml
@model List<PracticaAdoNet.Models.ViewModels.HeroeViewModels>
@{
    ViewBag.Title = "Index";
}

<h2>Heroes:</h2>
@if (TempData["MensajeExito"] != null)
{
    <div class="alert alert-success">
        @TempData["MensajeExito"]
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}

@if (Model != null && Model.Any())
{
    foreach (var heroe in Model)
    {
        <h3>Nombre = @heroe.Nombre</h3>
        <p>Clase = <b>@heroe.Clase</b></p>
        <p>Nivel = <b>@heroe.Nivel</b></p>

        using (Html.BeginForm("DeleteHeroeById", "Heroe", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden("id", heroe.Id)
            <button type="submit" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que quieres eliminar a @heroe.Nombre?');">Eliminar Heroe</button>
        }

        using (Html.BeginForm("FormularioEdicion","Heroe",FormMethod.Get))
        {
            @Html.AntiForgeryToken();
            @Html.Hidden("id",heroe.Id)
            <button class="btn btn-primary" type="submit">
                Editar
            </button>
        }
        <hr />
    }
}
else
{
    <h3>No hay heroes disponibles</h3>
}

PracticaAdoNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Heroe")</li>
                    <li>@Html.ActionLink("Crear heroe", "CreateHeroe", "Heroe")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>